#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Obtener la rama actual
current_branch="$(git rev-parse --abbrev-ref HEAD)"

# Bloquear pushes directos a main y develop
if [ "$current_branch" = "main" ] || [ "$current_branch" = "develop" ]; then
  echo "No puedes realizar push en '$current_branch'. Crea una nueva rama y utiliza Pull Requests para cambios en main o develop."
  exit 1
fi

echo "Ejecutando pruebas automáticas antes del push..."

# Ejecutar pruebas
npm test